### ISSUE TITLE
Not getting latest version on Bower

### ISSUE THREAD

**Issue by figalex** [davej/classy-computed#6]
When I do ```bower install classy-computed --save``` I get the version that still uses ```classy-core``` module instead of ```classy.core``` and it crashes when I run my app.

**Comment by davej** [comment]
Oops, looks like I forgot to publish the 1.2.1 release which fixes this. I've just published 1.2.2 so it should be fixed now. Thanks for reporting this issue.

**Comment by figalex** [comment]
Btw, your hidden easter egg on the working example is not working haha

**Comment by davej** [comment]
Damn it! I'll have to host Carlton myself somewhere.

Here's a mirror so you don't feel like you missed out! :-P 

![](http://25.media.tumblr.com/tumblr_mc08ok3e1V1rz3uwxo1_400.gif)

**Comment by figalex** [comment]
Haha thanks man!
